version: '3.8'

services:
  nginx-static:
    image: tokisero/nginx-static:0.1
    container_name: nginx-static
    restart: unless-stopped
    networks:
      - project-net

  apache:
    image: tokisero/apache:0.1
    container_name: apache
    restart: unless-stopped
    networks:
      - project-net

  red:
    image: tokisero/red:0.1
    container_name: red
    restart: unless-stopped
    networks:
      - project-net

  blue:
    image: tokisero/blue:0.1
    container_name: blue
    restart: unless-stopped
    networks:
      - project-net

  nginx-proxy:
    image: tokisero/nginx-proxy:0.1
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:8000"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - project-net
    depends_on:
      - nginx-static
      - apache
      - red
      - blue

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - project-net
    depends_on:
      - nginx-proxy

networks:
  project-net:
    driver: bridge